schema_version = "1.0.0"

id = "polyzamboni"
version = "1.3.1"
name = "PolyZamboni"
tagline = "Papercraft in Blender"
maintainer = "Anton Florey <anton.florey@googlemail.com>"
type = "add-on"
website = "https://github.com/AntonFlorey/PolyZamboni"
tags = ["3D View", "Import-Export"]
blender_version_min = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "macos-arm64", "linux-x64", "macos-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"

# 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
    "./wheels/contourpy-1.3.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/contourpy-1.3.3-cp313-cp313-macosx_10_13_x86_64.whl",
    "./wheels/contourpy-1.3.3-cp313-cp313-macosx_11_0_arm64.whl",
    "./wheels/contourpy-1.3.3-cp313-cp313-win_amd64.whl",
    "./wheels/cycler-0.12.1-py3-none-any.whl",
    "./wheels/fonttools-4.62.1-cp313-cp313-macosx_10_13_universal2.whl",
    "./wheels/fonttools-4.62.1-cp313-cp313-macosx_10_13_x86_64.whl",
    "./wheels/fonttools-4.62.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/fonttools-4.62.1-cp313-cp313-win_amd64.whl",
    "./wheels/kiwisolver-1.5.0-cp313-cp313-macosx_10_13_x86_64.whl",
    "./wheels/kiwisolver-1.5.0-cp313-cp313-macosx_11_0_arm64.whl",
    "./wheels/kiwisolver-1.5.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/kiwisolver-1.5.0-cp313-cp313-win_amd64.whl",
    "./wheels/matplotlib-3.10.9-cp313-cp313-macosx_10_13_x86_64.whl",
    "./wheels/matplotlib-3.10.9-cp313-cp313-macosx_11_0_arm64.whl",
    "./wheels/matplotlib-3.10.9-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/matplotlib-3.10.9-cp313-cp313-win_amd64.whl",
    "./wheels/networkx-3.6.1-py3-none-any.whl",
    "./wheels/packaging-26.2-py3-none-any.whl",
    "./wheels/pillow-12.2.0-cp313-cp313-macosx_10_13_x86_64.whl",
    "./wheels/pillow-12.2.0-cp313-cp313-macosx_11_0_arm64.whl",
    "./wheels/pillow-12.2.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/pillow-12.2.0-cp313-cp313-win_amd64.whl",
    "./wheels/pyparsing-3.3.2-py3-none-any.whl",
    "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
    "./wheels/six-1.17.0-py2.py3-none-any.whl",
]

[permissions]
files = "Export PDF/SVG to disk"
